[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama-chat"
version = "1.4.0"
description = "An Ollama chat web application"
readme = "README.md"
license = "MIT"
keywords = ["ollama", "chatbot", "conversational AI", "artificial intelligence", "AI"]
authors = [
    {name = "Craig A. Hobbs", email = "craigahobbs@gmail.com"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Communications :: Chat",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Utilities"
]
dependencies = [
    "bare-script >= 5.1.0, < 5.2.0",
    "chisel >= 2.4.0, < 2.5.0",
    "urllib3 >= 2.5.0",
    "waitress >= 3.0.0"
]

[project.urls]
Homepage = "https://github.com/craigahobbs/ollama-chat"

[project.scripts]
ollama-chat = "ollama_chat.main:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["ollama_chat", "ollama_chat.static"]

[tool.setuptools.package-data]
ollama_chat = [
    "static/*.bare",
    "static/*.html",
    "static/*.smd"
]
